Name: dd
Host: 0.0.0.0
Port: 8848
Log:
  Encoding: plain
DevLink:
  Mode: mqtt
  SubMode: emq
  Mqtt:
    ClientID: dd.rpc
    Pass: iThings
    User: ddsvr
    Brokers:
      - tcp://172.19.0.7:1883
Event:
  Mode: nats
  Nats:
    Url: nats://172.19.0.2:4222