#设备管理模块配置-dmsvr
Name: dm.rpc
ListenOn: 127.0.0.1:9081
CpuThreshold: 0
Timeout: 1000000
Log:
  Encoding: plain
Database:
  DBType: mysql
  DSN: root:password@tcp(172.19.0.4:3306)/iThings?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
CacheRedis:
  - Host: 172.19.0.5:6379
    Pass:
    Type: node
TDengine:
  DataSource: root:taosdata@http(172.19.0.6:6041)/iThings?readBufferSize=52428800
AuthWhite:
  Users:
    - UserName: ddsvr
      Password: iThings
OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: 172.19.0.10:9000
  CustomHost: /api/v1/oss
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false
Event:
  Nats:
    Url: nats://172.19.0.2:4222
OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: 172.19.0.10:9000
  CustomHost: /api/v1/oss
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false