Name: timedscheduler.rpc
ListenOn: 0.0.0.0:9284

Event:
  Mode: natsJs
CacheRedis:
  - Host: redis:6379
    Pass:
    Type: node
#Database:
#  DBType: pgsql
#  DSN: host=127.0.0.1 user= password= dbname=gleketest port=5432 sslmode=disable TimeZone=Asia/Shanghai
Database:
  IsInitTable: false
  DBType: mysql
  DSN: root:password@tcp(mariadb:3306)/iThings?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai