#系统管理模块配置-syssvr
Name: sys.rpc
ListenOn: 0.0.0.0:9180
CpuThreshold: 0
Etcd:
  Hosts:
    - etcd:2379
  Key: sys.rpc
Log:
  Encoding: plain
  #Mode: file
Database:
  DBType: mysql
  DSN: root:password@tcp(mariadb:3306)/iThings?charset=utf8mb4&collation=utf8mb4_bin&parseTime=true&loc=Asia%2FShanghai
#  DBType: pgsql
#  DSN: pgsql:host=localhost;port=5432;dbname=ithings;user=postgres;password=password
CacheRedis:
  - Host: 127.0.0.1:6379
    Pass:
    Type: node
UserToken:
  AccessSecret: ad879037-c7a4-4063-9236-6bfc35d54b7d
  AccessExpire: 36000000 #有效期为一小时
WexinMiniprogram:
  Open: true
  AppID: wx0a8aabe3ca57d4af
  AppSecret: f77f42b81e055ae8be41211cb0389b7d
UserOpt:
  NeedUserName: true
  NeedPassWord: true
  PassLevel: 2
OssConf:
  OssType: minio
  PublicBucketName: ithings-public
  PrivateBucketName: ithings-private
  TemporaryBucketName: ithings-temporary
  AccessKeyID: root
  AccessKeySecret: password
  Location: minio:9000
  ConnectTimeout: 6000
  ReadWriteTimeout: 60000
  UseSSL: false
Map:
  Mode: gaode
  AccessKey: be1c4f2f5f387fe516dc4761847307cb
  AccessSecret: 8bcb70bd3be24924a37c0bc2b93573d7
WrongPasswordCounter:
  Captcha: 4 # 连续输错密码次数上限，需要输验证码
  Account:
    - triggerTimes: 8  # 触发次数 默认 8
      statistics: 5    # 统计时间 默认 5 单位：分钟
      forbiddenTime: 2 # 冻结时长 默认 2 单位：分钟
  Ip:
    - triggerTimes: 8  # 触发次数 默认 8
      statistics: 5    # 统计时间 默认 5 单位：分钟
      forbiddenTime: 2 # 冻结时长 默认 2 单位：分钟
Event:
  Nats:
    Url: nats://nats:4222